import { Injectable } from '@nestjs/common';
import { PrismaService } from '@/shared/infrastructure/persistence/prisma/prisma.service';
import { UserRepository } from '../../domain/repositories/user.repository';
import { User } from '../../domain/entities/user.entity';
import { UserMapper } from './user.mapper';

@Injectable()
export class PrismaUserRepository implements UserRepository {
  constructor(private prisma: PrismaService) {}

  async create(user: User): Promise<User> {
    const data = UserMapper.toPersistence(user);
    // Remove ID if it's generated by DB, but here schema says default(uuid()), 
    // however usually domain entity has ID.
    // Let's assume we pass data without ID if it's new, but our domain entity has ID.
    // Actually, clean arch usually separates "NewUser" from "User". 
    // For simplicity, we will use upsert or just create.
    // If ID is present in domain entity, we might want to respect it (if UUID generated by domain)
    // or ignore it if generated by DB.
    // For this MVP, let's assume domain generates UUID or we let DB do it and update entity.
    
    // In this specific schema: id String @id @default(uuid())
    // We can omit ID in create if we want DB to generate it.
    
    const { id, ...rest } = data;
    
    // If the domain entity already has an ID (e.g. passed from frontend or generated in usecase), use it.
    // If not, let Prisma generate it.
    
    const created = await this.prisma.user.create({
      data: {
        ...rest,
        id: id || undefined,
      },
    });
    return UserMapper.toDomain(created);
  }

  async findByEmail(email: string): Promise<User | null> {
    const found = await this.prisma.user.findUnique({
      where: { email },
    });
    return found ? UserMapper.toDomain(found) : null;
  }

  async findById(id: string): Promise<User | null> {
    const found = await this.prisma.user.findUnique({
      where: { id },
    });
    return found ? UserMapper.toDomain(found) : null;
  }
}
