import { Injectable } from '@nestjs/common';
import { UserRepository } from '../../domain/repositories/user.repository';
import { User } from '../../domain/entities/user.entity';

@Injectable()
export class CreateUserUseCase {
  constructor(private readonly userRepository: UserRepository) {}

  async execute(dto: { name: string; email: string; image?: string }): Promise<User> {
    // Assuming ID is generated by DB or we generate it here.
    // Ideally we should check if user exists, but the controller/service did that or DB constraints handle it.
    // The previous logic was "create if not exists" inside Auth, but here is just "Create".
    
    const user = new User(
      '', // ID placeholder, will be effectively ignored or generated
      dto.email,
      dto.name,
      'ADOPTER', // default role
      new Date(),
      new Date(),
      null,
      dto.image
    );

    return this.userRepository.create(user);
  }
}
